### ISSUE TITLE
font issues with tmux/screen/byobu :

### ISSUE THREAD

**Issue by matth-c3** [bertrandmartel/aws-ssm-session#5]
Hello @bertrandmartel , 

great library, just a quick question, I use byobu ( on top of tmux / screen ) and I notice that some characters are not render correctly : 

![image](https://user-images.githubusercontent.com/30625765/110205828-1f61d500-7e2f-11eb-97f0-a8c30556a1b0.png)

Did you face the same issue maybe ? 

Thanks

**Comment by bertrandmartel** [comment]
hello @matth-c3 , are you using the nodejs example from [here](https://github.com/bertrandmartel/aws-ssm-session#nodejs) ?  I've installed byobu but could not reproduced the issue. maybe an utf8 issue; what is the result of the `locale` command on your shell ? (in byobu)

**Comment by matth-c3** [comment]
its the browser example, maybe that's the reason. 

Im using a centos 8, the locale are en_US.UTF-8 and the TERM is (screen), when starting byobu. 

On which distribution did you test ? It could be an OS issue

Thanks

**Comment by bertrandmartel** [comment]
I've just tried on the browser connecting to ec2 instance with amazon linux and didn't reproduce the issue. I've installed byobu on the instance and launched it without any weird character showing up. Do you experience the same in AWS console SSM manager when connecting to the instance ?

**Comment by matth-c3** [comment]
Hello @bertrandmartel , 

I guess it comes from the OS/distibution, Im getting the same issue when I start a session directly using the aws cli. 

I will do the test with a amazon linux image. I was using an external instance ( hybrid mode ) hosted on my local K8s. 

I will close the ticket afterwards if you dont mind, just in case I find something. 

Thanks

**Comment by matth-c3** [comment]
Hello @bertrandmartel , 

I did the test with the amazon linux 2 image provided by AWS (for docker). 

I installed byobu as follow : `yum install --enablerepo=epel byobu`  

Once I connect  using the browser example ( using `http-server  -p 3000` ) , I still have the same issue 

![image](https://user-images.githubusercontent.com/30625765/110225253-9e3f2800-7e98-11eb-9aff-3a2d4db99201.png)

The weird character appears when splitting the screen : `shift + F2` or `control + F2`. 

Did you proceed differently ? 

Thanks

**Comment by bertrandmartel** [comment]
Can you try with AWS console SSM, is this not displaying the characters there ?

I've managed to split horizontally and didn't reproduce on amazon linux 2 :
![byobu](https://user-images.githubusercontent.com/5183022/110226066-e471a700-7eeb-11eb-8902-62ad20ba059d.png)

**Comment by matth-c3** [comment]
Hello @bertrandmartel , 

Im not sure if I did not missed something on AWS Level ( maybe IAM ), because the session hangs when I start it from the AWS console and I see the following error : 

![image](https://user-images.githubusercontent.com/30625765/110227081-6ab8c980-7ea9-11eb-8734-bf880f35e00d.png)


looking at the log `/var/log/amazon/ssm/amazon-ssm-agent.log` on the instance, I can see that the session is successfully established, but the on the AWS console nothing is showing ( no prompt ). 

but from the aws cli ( on linux and windows powershell ), I can connect : 

![image](https://user-images.githubusercontent.com/30625765/110226983-6b049500-7ea8-11eb-8513-2a3bcdd8e70c.png)

![image](https://user-images.githubusercontent.com/30625765/110227006-96877f80-7ea8-11eb-9bc8-2a3c67b5b4c0.png)

and using you examples : 

![image](https://user-images.githubusercontent.com/30625765/110227023-ccc4ff00-7ea8-11eb-8cf9-99dddfbf46c8.png)

**Comment by bertrandmartel** [comment]
@matth-c3 thank you I've reproduced the issue, I'm working on it

**Comment by bertrandmartel** [comment]
@matth-c3  sorry for the late response, I've updated the lib to manage the unicode encoding/decoding when sending the data using `TextEncoder` and `TextDecoder` (and in nodejs `util.TextEncoder` / `util.TextDecoder`), this way byobu is correctly displaying the unicode characters, see [this sample code](https://github.com/bertrandmartel/aws-ssm-session#browser-1):

Specifically:

```javascript
terminal.write(textDecoder.decode(agentMessage.payload));
```
and 
```javascript
function initTerminal() {
  terminal = new Terminal(termOptions);
  terminal.open(document.getElementById("terminal"));
  terminal.onData(function (data) {
    ssm.sendText(socket, textEncoder.encode(data));
  });
  terminal.focus();
}
```
I've updated the `examples` folder to include a sample using webpack and using the latest version of xtermjs which could also fix some display issues that were present in the initial example (like the underlined text you may have experienced when exiting byobu)
